export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const FETCH_START = 'FETCH_START';
export const FETCH_END = 'FETCH_END';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_CANCEL = 'FETCH_CANCEL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LGOUT';

export const PENDING_TRANSACTIONS = 'PENDING_TRANSACTIONS';
export const TRANSACTION_DETAIL = 'TRANSACTION_DETAIL';
export const TRANSACTION_EXECUTION = 'TRANSACTION_EXECUTION';

export const BROADCAST_DETAIL = 'BROADCAST_DETAIL';
export const BROADCAST_STATUS = 'BROADCAST_STATUS';
export const BROADCAST_ERROR = 'BROADCAST_ERROR';

export const ALERT = 'ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SET_WALLET_FILES = 'SET_WALLET_FILES';

export const FETCHING_SEED = 'FETCHING_SEED';
export const FETCH_SEED_SUCCESS = 'FETCH_SEED_SUCCESS';
export const FETCH_SEED_FAILURE = 'FETCH_SEED_FAILURE';